version: '3'

volumes:
  ipython_data:
  postgres_data:

services:

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    image: redis:latest

  api:
    image: api
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    command: /usr/src/api/start.sh
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.${ENV}
    volumes:
      - ./api:/usr/src/api
      - ipython_data:/root/.ipython
    links:
      - postgres
      - redis
    ports:
      - 8000:8000

  nginx:
    image: nginx:stable
    volumes:
      - ./containers/nginx/conf.d/${ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./api:/usr/src/api
      - /usr/src/ssl:/usr/src/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    links:
      - api
