# Generated by Django 2.2.7 on 2023-11-13 04:21

import apps.book.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
                ('ISBN', models.CharField(max_length=50)),
                ('price', models.FloatField(help_text='dollar unit', max_length=25)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.book.models.upload_to, verbose_name='Book cover')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
